name = "PaperTemplate"
uuid = "00000000-0000-0000-0000-000000000000"
authors = ["James Azam <james.m.azam@gmail.com>"]
version = "0.1.0"

[deps]
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"

# Add your Julia dependencies here
# Common packages for scientific computing:
# DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
# CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
# Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
# StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
# Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"

[compat]
julia = "1.9"

[extras]
# Test dependencies
# Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
# test = ["Test"]
